version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2-fpm-browsers
        environment:
          - DB_USER=homestead
          - DB_PASSWORD=secret
          - DB_NAME=wp_test
          - DB_HOST=127.0.0.1
      - image: circleci/mysql:5.7.18
        environment:
          - MYSQL_ROOT_PASSWORD=secret
          - MYSQL_DATABASE=wp_test
          - MYSQL_USER=homestead
          - MYSQL_PASSWORD=secret
    working_directory: ~/wp-bonnier-sitemap
    steps:
      - checkout
      - run:
         name: Install PHP libzip-dev
         command: sudo apt-get install -y libzip-dev libpng-dev
      - run:
         name: Install PHP Modules
         command: sudo -E docker-php-ext-install zip pdo mysqli pdo_mysql gd
         
      - run: sudo composer self-update --1   
      
      - run: composer clearcache
      - run: composer config --global --auth http-basic.repo.packagist.com interactive 74ca79b1f66c8b04539f247c3b00c85839550ca24ba0f6517d29d7ae34f6
      - run: php -d memory_limit=4096M /usr/local/bin/composer update
      
      # - restore_cache:
      #     keys:
      #       - composer-v1-{{ checksum "composer.lock" }}
      #       - composer-v1-

     #  - save_cache:
     #      key: composer-v1-{{ checksum "composer.lock" }}
     #      paths:
     #        - vendor
     #        - web/wp
    
      - run:
          name: Run Unit Tests
          command: composer unit
      - run:
          name: Run Integration Tests
          command: composer integration
